/* Generated by AN DISI Unibo */ 
package it.unibo.weight_mock

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Weight_mock ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("Starting WeightMock")
					}
					 transition( edgeName="goto",targetState="sendData", cond=doswitch() )
				}	 
				state("sendData") { //this:State
					action { //it:State
						forward("weightData", "weightData(50)" ,"weight_sensor" ) 
						delay(5000) 
						forward("weightData", "weightData(45)" ,"weight_sensor" ) 
						delay(5000) 
						forward("weightData", "weightData(0)" ,"weight_sensor" ) 
					}
				}	 
			}
		}
}
