/* Generated by AN DISI Unibo */ 
package it.unibo.trolleyintermediary

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Trolleyintermediary ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				var CMD = ""
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("wait") { //this:State
					action { //it:State
					}
					 transition(edgeName="t021",targetState="handleCmd",cond=whenDispatch("basicmd"))
				}	 
				state("handleCmd") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("basicmd(CMD)"), Term.createTerm("basicmd(CMD)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
												CMD = payloadArg(0)
								if(  CMD == "l" || CMD == "r"  
								 ){forward("cmd", "cmd($CMD)" ,"basicrobot" ) 
								}
						}
					}
					 transition( edgeName="goto",targetState="stepMove", cond=doswitchGuarded({ CMD == "w"  
					}) )
					transition( edgeName="goto",targetState="wait", cond=doswitchGuarded({! ( CMD == "w"  
					) }) )
				}	 
				state("stepMove") { //this:State
					action { //it:State
						request("step", "step(175)" ,"basicrobot" )  
					}
					 transition(edgeName="t022",targetState="wait",cond=whenReply("stepdone"))
					transition(edgeName="t023",targetState="stepFailed",cond=whenReply("stepfail"))
				}	 
				state("stepFailed") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("stepfail(DURATION,CAUSE)"), Term.createTerm("stepfail(DURATION,OBSTACLE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
												var DIST = payloadArg(0) //sostituire con pathexecutil.waitUser("Reposition the robot",10000)
								request("step", "step($DIST)" ,"basicrobot" )  
						}
					}
					 transition(edgeName="t124",targetState="wait",cond=whenReply("stepdone"))
					transition(edgeName="t125",targetState="stepFailed",cond=whenReply("stepfail"))
				}	 
			}
		}
}
