/* Generated by AN DISI Unibo */ 
package it.unibo.ctxparkmanager
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "192.168.1.78", this, "client.pl", "sysRules.pl"
	)
}

