/* Generated by AN DISI Unibo */ 
package it.unibo.parkingservicestatusgui

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Parkingservicestatusgui ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("Starting ParkingServiceStatusGUI.")
						coap.actorQakStateCoapObserver.activate(myself)
					}
				}	 
				state("printAndStop") { //this:State
					action { //it:State
						 println("Stato sistema:" + coap.actorQakStateCoapObserver.readResponse())  
						delay(5000) 
						forward("stop", "stop(stop)" ,"parkmanagerservice" ) 
						delay(15000) 
						forward("stop", "stop(start)" ,"parkmanagerservice" ) 
					}
					 transition(edgeName="t035",targetState="eventReceived",cond=whenEvent("sonarevent"))
				}	 
				state("eventReceived") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
					}
				}	 
			}
		}
}
