/* Generated by AN DISI Unibo */ 
package it.unibo.parkingservicestatusgui

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Parkingservicestatusgui ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("Starting ParkingServiceStatusGUI.")
						coap.actorQakStateCoapObserver.activate(myself)
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("wait") { //this:State
					action { //it:State
						 println("Stato sistema:" + coap.actorQakStateCoapObserver.readResponse())  
					}
					 transition(edgeName="t037",targetState="eventReceived",cond=whenEvent("sonarevent"))
					transition(edgeName="t038",targetState="thermEvent",cond=whenEvent("thermometerevent"))
				}	 
				state("eventReceived") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
					}
				}	 
				state("thermEvent") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("thermometerevent(X)"), Term.createTerm("thermometerevent(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var type = "${payloadArg(0)}"  
								if(  type == "above"  
								 ){updateResourceRep( "received: above"  
								)
								}
								else
								 {updateResourceRep( "received: below"  
								 )
								 }
						}
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
			}
		}
}
