/* Generated by AN DISI Unibo */ 
package it.unibo.park_manager_service

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Park_manager_service ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 
				var counter=0 
				var FREE_INDOOR=true
				var x = 0
				var y = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						discardMessages = false
						solve("consult('parking.pl')","") //set resVar	
						solve("dynamic('freeSlot/1')","") //set resVar	
						solve("unoccupySlot(1)","") //set resVar	
						println("Starting ParkManagerService.")
					}
					 transition( edgeName="goto",targetState="accept", cond=doswitch() )
				}	 
				state("accept") { //this:State
					action { //it:State
						println("ParkManagerServing accepting client requests...")
					}
					 transition(edgeName="clientMsg4",targetState="handleClientRequest",cond=whenRequest("clientRequest"))
					transition(edgeName="clientMsg5",targetState="handleCarEnter",cond=whenRequest("carenter"))
					transition(edgeName="clientMsg6",targetState="handleClientOut",cond=whenDispatch("outTokenid"))
				}	 
				state("handleClientRequest") { //this:State
					action { //it:State
						println("ParkManagerService handling client request")
						if( checkMsgContent( Term.createTerm("clientRequest(X)"), Term.createTerm("clientRequest(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val requestType = "${payloadArg(0)}"  
								if(  requestType == "in"  
								 ){if(  FREE_INDOOR  
								 ){solve("getFreeSlot(S)","") //set resVar	
								 val SLOTNUM = getCurSol("S")  
								solve("occupySlot($SLOTNUM)","") //set resVar	
								answer("clientRequest", "enter", "enter($SLOTNUM)"   )  
								}
								}
						}
					}
					 transition( edgeName="goto",targetState="accept", cond=doswitch() )
				}	 
				state("handleCarEnter") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("carenter(SLOTNUM)"), Term.createTerm("carenter(SLOTNUM)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val SLOTNUM = payloadArg(0).toInt()  
								updateResourceRep( ""+SLOTNUM  
								)
								solve("indoor(X,Y)","") //set resVar	
								 x = getCurSol("X").toString().toInt()  
								 y = getCurSol("Y").toString().toInt()  
								solve("getCoordinates($SLOTNUM,X,Y)","") //set resVar	
								 x = getCurSol("X").toString().toInt()  
								 y = getCurSol("Y").toString().toInt()  
								 val TOKENID = "$SLOTNUM"+"$counter"  
								 counter++  
								answer("carenter", "receipt", "receipt($TOKENID)"   )  
						}
						stateTimer = TimerActor("timer_handleCarEnter", 
							scope, context!!, "local_tout_park_manager_service_handleCarEnter", 1000.toLong() )
					}
					 transition(edgeName="t37",targetState="moveTrolleyHome",cond=whenTimeout("local_tout_park_manager_service_handleCarEnter"))   
					transition(edgeName="t38",targetState="handleClientRequest",cond=whenRequest("clientRequest"))
					transition(edgeName="t39",targetState="handleCarEnter",cond=whenRequest("carenter"))
					transition(edgeName="t310",targetState="handleClientOut",cond=whenDispatch("outTokenid"))
				}	 
				state("handleClientOut") { //this:State
					action { //it:State
						println("ParkManagerServing out.")
						if( checkMsgContent( Term.createTerm("outTokenid(TOKENID)"), Term.createTerm("outTokenid(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val TOKENID = "${payloadArg(0)}"  
								 val SLOTNUM =  TOKENID.first()  
								println("TOKENID $TOKENID")
								updateResourceRep( ""+TOKENID  
								)
								solve("getCoordinates($SLOTNUM,X,Y)","") //set resVar	
								 x = getCurSol("X").toString().toInt()  
								 y = getCurSol("Y").toString().toInt()  
								solve("outdoor(X,Y)","") //set resVar	
								 x = getCurSol("X").toString().toInt()  
								 y = getCurSol("Y").toString().toInt()  
								solve("unoccupySlot($SLOTNUM)","") //set resVar	
						}
						stateTimer = TimerActor("timer_handleClientOut", 
							scope, context!!, "local_tout_park_manager_service_handleClientOut", 1000.toLong() )
					}
					 transition(edgeName="t411",targetState="moveTrolleyHome",cond=whenTimeout("local_tout_park_manager_service_handleClientOut"))   
					transition(edgeName="t412",targetState="handleClientRequest",cond=whenRequest("clientRequest"))
					transition(edgeName="t413",targetState="handleCarEnter",cond=whenRequest("carenter"))
					transition(edgeName="t414",targetState="handleClientOut",cond=whenDispatch("outTokenid"))
				}	 
				state("moveTrolleyHome") { //this:State
					action { //it:State
						solve("home(X,Y)","") //set resVar	
						 x = getCurSol("X").toString().toInt()  
						 y = getCurSol("Y").toString().toInt()  
					}
					 transition( edgeName="goto",targetState="accept", cond=doswitch() )
				}	 
			}
		}
}
