/* Generated by AN DISI Unibo */ 
package it.unibo.ctxclient
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "192.168.0.68", this, "model.pl", "sysRules.pl"
	)
}

