/* Generated by AN DISI Unibo */ 
package it.unibo.weightlogic

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Weightlogic ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("Starting Weight logic.")
						solve("consult('weightapplogic.pl')","") //set resVar	
						solve("dynamic('prevWeight/1')","") //set resVar	
						solve("init(X)","") //set resVar	
						 val INITSTATUS = getCurSol("X").toString()  
						forward("weightstatusupdate", "weightstatusupdate($INITSTATUS)" ,"weightsensor" ) 
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("wait") { //this:State
					action { //it:State
					}
					 transition(edgeName="t02",targetState="applylogic",cond=whenEvent("localweightupdate"))
				}	 
				state("applylogic") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("localweightupdate(W)"), Term.createTerm("localweightupdate(W)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val WEIGHT = "${payloadArg(0)}"  
								solve("modifyStatus($WEIGHT,SOL)","") //set resVar	
								 val RESULT = getCurSol("SOL").toString()  
								if(  RESULT=="true"  
								 ){solve("getStatus($WEIGHT,X)","") //set resVar	
								 var STATUS = getCurSol("X").toString()  
								forward("weightstatusupdate", "weightstatusupdate($STATUS)" ,"weightsensor" ) 
								}
						}
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
			}
		}
}
