/* Generated by AN DISI Unibo */ 
package it.unibo.thermometer

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Thermometer ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("Starting Thermometer.")
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("wait") { //this:State
					action { //it:State
						println("Thermometer waiting for data...")
					}
					 transition(edgeName="t00",targetState="handleData",cond=whenDispatch("tempData"))
					transition(edgeName="t01",targetState="updateStatus",cond=whenDispatch("thermstatusupdate"))
				}	 
				state("handleData") { //this:State
					action { //it:State
						println("Thermometer received data")
						if( checkMsgContent( Term.createTerm("tempData(W)"), Term.createTerm("tempData(W)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var TEMP = "${payloadArg(0)}"  
								emit("local_thermupdate", "local_thermupdate($TEMP)" ) 
						}
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("updateStatus") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("thermstatusupdate(S)"), Term.createTerm("thermstatusupdate(S)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var status = "${payloadArg(0)}"  
								updateResourceRep( status  
								)
								println("$status")
						}
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
			}
		}
}
