/* Generated by AN DISI Unibo */ 
package it.unibo.client

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Client ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 var TOKENID = ""  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("Starting Client.")
					}
					 transition( edgeName="goto",targetState="requestIn", cond=doswitch() )
				}	 
				state("requestIn") { //this:State
					action { //it:State
						println("Client request to park.")
						request("clientRequest", "clientRequest(in)" ,"park_manager_service" )  
					}
					 transition(edgeName="slotnumReceived2",targetState="handleSlotnum",cond=whenReply("replySlotnum"))
				}	 
				state("handleSlotnum") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("Client SLOTNUM received.")
						if( checkMsgContent( Term.createTerm("replySlotum(X)"), Term.createTerm("replySlotnum(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val SLOTNUM = payloadArg(0)  
								println("received slotnum: $SLOTNUM")
						}
					}
					 transition(edgeName="tokenidReceived3",targetState="handleTokenid",cond=whenDispatch("replyTokenid"))
				}	 
				state("handleTokenid") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("Client TOKENID received.")
						if( checkMsgContent( Term.createTerm("replyTokenid(X)"), Term.createTerm("replyTokenid(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 TOKENID = "${payloadArg(0)}"  
								println("received tokenid: $TOKENID")
						}
						stateTimer = TimerActor("timer_handleTokenid", 
							scope, context!!, "local_tout_client_handleTokenid", 1000.toLong() )
					}
					 transition(edgeName="out4",targetState="requestOut",cond=whenTimeout("local_tout_client_handleTokenid"))   
				}	 
				state("requestOut") { //this:State
					action { //it:State
						println("Client request to exit sent.")
						forward("outTokenid", "outTokenid($TOKENID)" ,"park_manager_service" ) 
					}
				}	 
			}
		}
}
