/* Generated by AN DISI Unibo */ 
package it.unibo.client

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Client ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 var TOKENID = ""
			 var SLOTNUM = 0   
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("Starting Client.")
					}
					 transition( edgeName="goto",targetState="requestIn", cond=doswitch() )
				}	 
				state("requestIn") { //this:State
					action { //it:State
						println("Client request to park.")
						request("clientRequest", "clientRequest(in)" ,"park_manager_service" )  
					}
					 transition(edgeName="t00",targetState="handleSlotnum",cond=whenReply("enter"))
				}	 
				state("handleSlotnum") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("enter(SLOTNUM)"), Term.createTerm("enter(SLOTNUM)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 SLOTNUM = payloadArg(0).toInt()  
								println("received slotnum: $SLOTNUM")
						}
					}
					 transition( edgeName="goto",targetState="end", cond=doswitchGuarded({ SLOTNUM==0  
					}) )
					transition( edgeName="goto",targetState="moveIndoor", cond=doswitchGuarded({! ( SLOTNUM==0  
					) }) )
				}	 
				state("moveIndoor") { //this:State
					action { //it:State
						request("carenter", "carenter($SLOTNUM)" ,"park_manager_service" )  
					}
					 transition(edgeName="t01",targetState="handleTokenid",cond=whenReply("replyTokenid"))
				}	 
				state("handleTokenid") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("replyTokenid(TOKENID)"), Term.createTerm("replyTokenid(TOKEN)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 TOKENID = "${payloadArg(0)}"  
								println("received tokenid: $TOKENID")
						}
						stateTimer = TimerActor("timer_handleTokenid", 
							scope, context!!, "local_tout_client_handleTokenid", 1000.toLong() )
					}
					 transition(edgeName="out2",targetState="requestOut",cond=whenTimeout("local_tout_client_handleTokenid"))   
				}	 
				state("requestOut") { //this:State
					action { //it:State
						println("Client request to exit sent.")
						forward("outTokenid", "outTokenid($TOKENID)" ,"park_manager_service" ) 
					}
					 transition( edgeName="goto",targetState="end", cond=doswitch() )
				}	 
				state("end") { //this:State
					action { //it:State
						println("Client finished")
					}
				}	 
			}
		}
}
